### ISSUE TITLE
Closing file is redundant while using `with` keyword

### ISSUE THREAD

**Issue by hoanhan101** [DungLe13/NLP-for-Game#1]
According Python's documentation:
> It is good practice to use the with keyword when dealing with file objects. The advantage is that the file is properly closed after its suite finishes, even if an exception is raised at some point.

Basically, there's no need to close the file when you're already using `with`.

These are lines number associating with files that can be deleted:
- `grammar_checker.py`: line 17 and 25
- `knowledge_rep.py`:line 38
- `parser_sample.py`: line 29, 35

You're welcome!

**Comment by DungLe13** [comment]
Resolved! Thanks =))

**Comment by hoanhan101** [comment]
You might want to take another look because `grammar_check.py` and `parser_sample.py` are still unchanged. Other than that, the remaining files look good!
